name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write

jobs:

  # --------------------------------
  # 1. GITLEAKS
  # --------------------------------
  gitleaks:
    name: Secret Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # --------------------------------
  # 2. SONARCLOUD
  # --------------------------------
  sonarqube:
    name: SonarQube Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=IliosDigital_Devsecops-test
            -Dsonar.organization=iliosdigital


  # --------------------------------
  # 3. BUILD DOCKER IMAGE
  # --------------------------------
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    needs:
      - gitleaks
      - sonarqube

    steps:
      - name: Checkout source
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Build Docker image
        run: |
          docker build \
            -t devsecops-demo:${{ github.sha }} .


  # --------------------------------
  # 4. TRIVY
  # --------------------------------
  trivy:
    name: Trivy Container Scan
    runs-on: ubuntu-latest

    needs:
      - docker-build

    steps:
      - name: Checkout source
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Build Docker image
        run: |
          docker build \
            -t devsecops-demo:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: devsecops-demo:${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      - name: Upload Trivy results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif
          category: trivy-container
